### ISSUE TITLE
Great Plugin But missing Recaptcha Plugin.

### ISSUE THREAD

**Issue by worldofsmarty** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#12]
This is a great Plugin. The only thing it's missing is the recaptcha attached to it to avoid spamming.

**Comment by MicaelRodrigues** [comment]
There's any update here?

**Comment by worldofsmarty** [comment]
Well we can use the alex recaptcha plugin along with this contact form. But the only problem is that the validation of the form takes place only after validation of the recaptcha. untill the recaptcha is ticked we cannot validate the form.

**Comment by ixperiencenl** [comment]
But the captcha is of course mandatory for submitting the form. You can use the 'require' tag to offer some usability to avoid headaches with visitors. Maybe it would be nice to offer multiple captcha plugins (text only or the reCaptcha/NoCaptcha for example).

**Comment by LaminSanneh** [comment]
New captcha feature integrated into plugin. Requires a google recaptcha account though, but pretty straightforward.
