### ISSUE TITLE
Docs how to use from partial

### ISSUE THREAD

**Issue by shrpne** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#13]
http://octobercms.com/plugin/laminsanneh-flexicontact/ajax-handler-contactformonmailsent-was-not-found 
Here you write that plugin have restriction to use in partial.
I found hacky way to make it work.

In partial put just markup of component.
And add component itself to layout.

It works for me, i found a lot of topics in support section of component. How about add this information to documentation?

Also `{{ SELF }}` or `{{ __SELF__ }}` not working for me, i need to use component alias instead.
Maybe because i use it in partial, i don't sure. 
This issue mentioned by other peoples in support section too.

**Comment by LaminSanneh** [comment]
Yes, that will work and I am glad you found a work around. However, I believe the point of the plugin is to make it as easy to use as possible without breaking usage incase of an upgrade. Not to knock your findings out but it does not qualify as documentation. It should be sufficient for people to find in support. Also, I believe the october creators have a good reason for limiting functions in partials.

Closing for now.
