### ISSUE TITLE
On each Submit, the email is sent twice.

### ISSUE THREAD

**Issue by WebShapedBiz** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#18]
I don't get this, I always end up with two emails, about one second apart and coming from the same source, according to Network tab in Chrome DevTools.

Cheers.

**Comment by tplessis** [comment]
Exactly the same trouble here.

**Comment by kieran21** [comment]
recommend you guys route through mailgun or similar so you can see email logs more accurately

**Comment by LaminSanneh** [comment]
You guys @WebShapedBiz , @tplessis  still having this issue. I couldn't replicate it.

**Comment by antonijap** [comment]
I have the same issue...

**Comment by kdon80** [comment]
The plugin sends two emails, one to the website owner, and the other one to the form submitter, correct? I think those guys are testing the form by providing their own email, so they receive two emails!

btw,there should be **an option to disable sending to the email to the submitter** as well.

This is from the code, sending one to post's email and another to the email provided in the settings:

```
        $message->replyTo(post('email'), post('name'))
            ->to(Settings::get('recipient_email'), Settings::get('recipient_name'))
            ->subject(Settings::get('subject'));
```

**Comment by kieran21** [comment]
@kdon80 reply-to is an additional header in the email it doesnt send another email.

**Comment by merodeador** [comment]
i also have this problem.

**Comment by joebuonocore** [comment]
Check and make sure that you only have {% framework extras %} once in your layout, and no {% framework %} if using extras. This happened to me a while back and that was the reason. Rookie mistake, but maybe it'll help someone.

**Comment by LaminSanneh** [comment]
Closing as could not replicate. Is anyone still having this issue?

**Comment by WebShapedBiz** [comment]
Thanx @joebuonocore, that slipped through my code checking.

**Comment by joebuonocore** [comment]
No problem @WebShapedBiz, took me a while to catch when it happened to me.
