### ISSUE TITLE
Server Captcha Validation Issue

### ISSUE THREAD

**Issue by kieran21** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#19]
Firstly, thanks Lamin for putting Flexi Contact together! It's nice to find exactly what you're looking for sometimes. 

Just noticed there was an update yesterday which included Google reCaptcha (nice!) so updated, got reCaptcha credentials etc. Works fine, unless I turn on Server Captcha Validation in backend Marketing > Flexi Contact Settings.

Running build 316 of OctoberCMS. 

Screenshot of where setting is turned on in OctoberCMS:
![capture](https://cloud.githubusercontent.com/assets/9548695/13619602/e698d1b6-e5ee-11e5-8e27-fdb284a0ac87.PNG)

Screenshot of error message generated on Submit click:
![error message](https://cloud.githubusercontent.com/assets/9548695/13619693/7a095074-e5ef-11e5-83fc-48552897765c.PNG)

I'll put that error text here:
`"Uncaught TypeError: Argument 1 passed to October\Rain\Foundation\Exception\Handler::report() must be an instance of Exception, instance of Error given, called in /srv/users/serverpilot/apps/ocrane/public/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 73 and defined in /srv/users/serverpilot/apps/ocrane/public/vendor/october/rain/src/Foundation/Exception/Handler.php:42
Stack trace:
#0 /srv/users/serverpilot/apps/ocrane/public/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(73): October\Rain\Foundation\Exception\Handler->report(Object(Error))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#2 {main}
  thrown" on line 42 of /srv/users/serverpilot/apps/ocrane/public/vendor/october/rain/src/Foundation/Exception/Handler.php`

**Comment by LaminSanneh** [comment]
Glad you found the update useful. I just retested with the server validation, works fine for me. I am on build 317. Have you done a composer update, that might help. If not, let me know.
Thanks for testing though.

**Comment by kieran21** [comment]
haven't tried a composer update will have to fiddle with installing composer - so far have survived with wizards. Just installed a fresh copy of October build 316 on a test server and FlexiContact 1.3.4. 

Now get the error every time form submit with captcha or not. Weird.

**Comment by LaminSanneh** [comment]
Hmm, thats strange, you shouldnt need to run composer update if you install through wizard, it should do that for you automatically. When I have time, I will install a fresh copy of october just to test.

Please keep me in the loop if any new developments come up your end.

**Comment by CoryWA** [comment]
I am encountering a similar issue.  I found a similar error was solved by installing a missing element for php7, but this one persists.  If I use server validation, I get that error.  Build 318.

**Comment by LaminSanneh** [comment]
Closing this as I couldn't replicate issue. Are you guys still having issues with this?
