### ISSUE TITLE
Should Have Ability to Disable Captcha

### ISSUE THREAD

**Issue by abass** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#20]
I am happy that you added the captcha, but you really should have a "toggle" function to turn it on/off from being required.

I have some sites that I would like a captcha, but others I do not want to waste the user's time with that. There's no possibly way for me to currently disable it though.

**Comment by LaminSanneh** [comment]
ok i will look into it. thanks for the suggestion.

**Comment by LaminSanneh** [comment]
Closing this as feature has been implemented
