### ISSUE TITLE
Viewing Individual Log in Contact Logs Broken

### ISSUE THREAD

**Issue by abass** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#21]
This happened a while ago but you fixed it. It seems to be happening again now. This error comes up when you try clicking on an individual log in the contact area:

![IMG](https://s3.amazonaws.com/f.cl.ly/items/2z0H32101y0H1p2e1d1q/Image%202016-03-12%20at%205.09.12%20PM.png?v=2bd0f94d)

**Comment by LaminSanneh** [comment]
I am sorry but this error is unrelated to my plugin. Seems it's caused by octomail plugin.

**Comment by abass** [comment]
Ah, sorry. I guess your plugins work closely with one another. I apologize!
