### ISSUE TITLE
Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by mkrell** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#5]
Hi. I've downloaded your plugin and it has worked before, and now I'm setting up the same site again on a different machine and I get this popup: 

```
Class 'GuzzleHttp\Client' not found
```

Both October and FlexiContact are updated so I'm not sure what is going wrong. Would this be a bug or is there something wrong with my machine?

**Comment by LaminSanneh** [comment]
Which line do you get this. Is it an error from my plugin?

**Comment by mkrell** [comment]
To be honest I have no clue how I fixed this, it was so long ago!

Reaching back into the foggy bits of my memory it might have been something as simple as doing a `composer install` or updating the `composer.json` file. Just don't remember.

**Comment by LaminSanneh** [comment]
Try doing a composer install in the plugin root directory. Seems the composer dependencies aren't installed properly for some reason.
