### ISSUE TITLE
I18N and L10N

### ISSUE THREAD

**Issue by mahony0** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#6]
I'm developing E-commerce system with October and using this plugin. If you can add lang folder and make texts and inputs dynamic -takes only 5-10 mins.- this plugin will be very useful for me and others. I can help editing the plugin btw. Thanks.

**Comment by FelixINX** [comment]
I have builded a new plugin http://octobercms.com/plugin/devinx-contactus for this. You can modify all the placeholder text. I am working on a new version with Translate Plugin.

**Comment by mahony0** [comment]
heh, it past nearly 1 and a half year since opening this issue. but it's ok, I'll take a look at your plugin in my spare time :))

**Comment by LaminSanneh** [comment]
@FelixINX , I know it's opensource and all but all you needed to do was ask for admin access if you needed to do such significant changes. I think its non-constructive to copy another plugin but feel free to do so. Opensource for the win. :-)
