### ISSUE TITLE
Problem with AJAX

### ISSUE THREAD

**Issue by ghost** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#9]
So there is a problem with sending my mail. I used custom markup and included the framework dependencies under the Javascript libraries just before the closing body tag. However, whenever I want to send a mail, the page reloads and this appears in my address bar, behind the address of the original page:

?name=name&email=mail%40mail.com&subject=subject&body=body

I'm using Jquery 2.1.4 (minified) in my custom theme.

**Comment by WebShapedBiz** [comment]
Same here.

**Comment by LaminSanneh** [comment]
Are you still having this issue. I will close but open to reopening if the issue is still there?

**Comment by WebShapedBiz** [comment]
I'm OK now, thank you.

**Comment by LaminSanneh** [comment]
Ok @WebShapedBiz thank you.
